// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_router.dart';

// **************************************************************************
// PrismRouterGenerator
// **************************************************************************

// Generated by prism_router_generator. Do not edit.
final class DetailsPage extends PrismPage {
  DetailsPage({required this.userId, required this.note, LocalKey? pageKey})
      : super(
          name: 'details',
          child: DetailsScreen(userId: userId, note: note),
          arguments: <String, Object?>{'userId': userId, 'note': note},
          tags: const <String>{'details'},
          key: pageKey,
        );

  final String userId;
  final String note;

  static PrismPage fromArgs(Map<String, Object?> arguments) {
    if (arguments case {'userId': String userId, 'note': String note}) {
      return DetailsPage(userId: userId, note: note);
    }
    return DetailsPage(
        userId: (arguments['userId'] as String?) ?? '',
        note: (arguments['note'] as String?) ?? '');
  }

  @override
  PrismPage pageBuilder(Map<String, Object?> arguments) => fromArgs(arguments);
}

final class HomePage extends PrismPage {
  HomePage({LocalKey? pageKey})
      : super(
          name: 'home',
          child: HomeScreen(),
          arguments: const <String, Object?>{},
          tags: null,
          key: pageKey,
        );

  static PrismPage fromArgs(Map<String, Object?> arguments) {
    return HomePage();
  }

  @override
  PrismPage pageBuilder(Map<String, Object?> arguments) => fromArgs(arguments);
}

final class MarketPage extends PrismPage {
  MarketPage({LocalKey? pageKey})
      : super(
          name: 'market',
          child: MarketScreen(),
          arguments: const <String, Object?>{},
          tags: null,
          key: pageKey,
        );

  static PrismPage fromArgs(Map<String, Object?> arguments) {
    return MarketPage();
  }

  @override
  PrismPage pageBuilder(Map<String, Object?> arguments) => fromArgs(arguments);
}

final class ProfilePage extends PrismPage {
  ProfilePage({LocalKey? pageKey})
      : super(
          name: 'profile',
          child: ProfileScreen(),
          arguments: const <String, Object?>{},
          tags: null,
          key: pageKey,
        );

  static PrismPage fromArgs(Map<String, Object?> arguments) {
    return ProfilePage();
  }

  @override
  PrismPage pageBuilder(Map<String, Object?> arguments) => fromArgs(arguments);
}

final class SettingsPage extends PrismPage {
  SettingsPage({required this.data, LocalKey? pageKey})
      : super(
          name: 'settings',
          child: SettingsScreen(data: data),
          arguments: <String, Object?>{'data': data},
          tags: const <String>{'settings'},
          key: pageKey,
        );

  final String data;

  static PrismPage fromArgs(Map<String, Object?> arguments) {
    if (arguments case {'data': String data}) {
      return SettingsPage(data: data);
    }
    return SettingsPage(data: (arguments['data'] as String?) ?? '');
  }

  @override
  PrismPage pageBuilder(Map<String, Object?> arguments) => fromArgs(arguments);

  @override
  Route<void> createRoute(BuildContext context) {
    return PageRouteBuilder<void>(
      settings: this,
      pageBuilder: (context, animation, secondaryAnimation) => child,
      transitionsBuilder: (context, animation, secondaryAnimation, child) {
        final curved =
            CurvedAnimation(parent: animation, curve: Curves.easeOutCubic);
        return FadeTransition(
          opacity: curved,
          child: ScaleTransition(scale: curved, child: child),
        );
      },
    );
  }
}

final class SettingsPage2 extends PrismPage {
  SettingsPage2({required this.data, LocalKey? pageKey})
      : super(
          name: 'settings2',
          child: SettingsScreen2(data: data),
          arguments: <String, Object?>{'data': data},
          tags: const <String>{'settings2'},
          key: pageKey,
        );

  final String data;

  static PrismPage fromArgs(Map<String, Object?> arguments) {
    if (arguments case {'data': String data}) {
      return SettingsPage2(data: data);
    }
    return SettingsPage2(data: (arguments['data'] as String?) ?? '');
  }

  @override
  PrismPage pageBuilder(Map<String, Object?> arguments) => fromArgs(arguments);

  @override
  Route<void> createRoute(BuildContext context) {
    return PageRouteBuilder<void>(
      settings: this,
      pageBuilder: (context, animation, secondaryAnimation) => child,
      transitionsBuilder: (context, animation, secondaryAnimation, child) {
        return FadeTransition(opacity: animation, child: child);
      },
    );
  }
}

final List<PrismRouteDefinition> appRoutes = <PrismRouteDefinition>[
  PrismRouteDefinition(name: 'details', builder: DetailsPage.fromArgs),
  PrismRouteDefinition(name: 'home', builder: HomePage.fromArgs),
  PrismRouteDefinition(name: 'market', builder: MarketPage.fromArgs),
  PrismRouteDefinition(name: 'profile', builder: ProfilePage.fromArgs),
  PrismRouteDefinition(name: 'settings', builder: SettingsPage.fromArgs),
  PrismRouteDefinition(name: 'settings2', builder: SettingsPage2.fromArgs),
];

final List<PrismPage> initialStack = <PrismPage>[
  HomePage(),
];

RouterConfig<Object> buildPrismRouterConfig({
  PrismWebHistoryMode webHistoryMode = PrismWebHistoryMode.entries,
  List<NavigatorObserver> observers = const <NavigatorObserver>[],
  TransitionDelegate<Object> transitionDelegate =
      const DefaultTransitionDelegate<Object>(),
  String? restorationScopeId,
  PrismGuard guards = const <PrismNavigationGuard>[],
}) {
  return PrismRouter.router(
    initialStack: initialStack,
    routes: appRoutes,
    webHistoryMode: webHistoryMode,
    observers: observers,
    transitionDelegate: transitionDelegate,
    restorationScopeId: restorationScopeId,
    guards: guards,
  );
}
